(function () {
  const LANGUAGES = {
    en: {
      name: "English",
      brand: { tagline: "Subtraction Edition" },
      a11y: { skip: "Skip to content" },
      loader: { text: "Getting your lessons" },
      progress: { title: "Your progress" },
      quizzes: {
        heading: "Your Stars",
        body: "Win 1 star for a pass, 2 for a great score and 3 for full marks. Pass all four to get your award.",
      },
      about: {
        heading: "About",
        card1: {
          title: "One idea at a time",
          body: "Every lesson teaches one thing, then lets you practise it.",
        },
        card2: {
          title: "Three languages",
          body: "Read and listen in English, Tagalog or Bisaya. Change it any time you like.",
        },
        card3: {
          title: "Works anywhere",
          body: "You do not need the internet. Everything works on your phone already.",
        },
      },
      name: {
        title: "What is your name?",
        desc: "We will put this name on your award.",
        label: "Your name",
        placeholder: "Type your name",
        save: "Save",
      },
      confirm: {
        title: "Stop the quiz?",
        body: "Your score this time will not be saved.",
        stay: "Keep playing",
        leave: "Stop",
      },
      footer: {
        text: "Fraction Fusion. Built for better math sessions.",
        meta: "Works offline",
      },
      nav: ["Home", "Lessons", "Stars", "About"],
      hero: {
        eyebrow: "Maths \u00b7 Subtraction Edition",
        title: "Let's Take Away Fractions!",
        intro:
          "Watch four short videos, then play a quiz after each one. Collect stars as you go.",
        start: "Start",
        quiz: "Play a Quiz",
      },
      lessons: {
        heading: "Pick a Lesson",
        body: "Start with number 1. Each lesson helps you with the next one.",
      },
      settings: {
        button: "Settings",
        title: "Settings",
        languageLabel: "Language",
        languageHelp: "Changes the words everywhere.",
        musicLabel: "Music",
        musicHelp: "Stops on its own when a video plays.",
      },
      quizText: {
        takeQuiz: "Play Quiz",
        videoSoonTitle: "Video coming soon",
        videoSoonBody: "This video is not here yet. You can still play the quiz.",
        highestScore: "Best score",
        bestPercentage: "Best mark",
        attempts: "Tries",
        question: "Question",
        of: "of",
        remaining: "to go",
        prev: "Back",
        next: "Next",
        finish: "Finish",
        pass: "Pass",
        fail: "Try again",
        excellent: "Brilliant!",
        good: "Well done!",
        keep: "Good try. Have another go.",
        viewSolutions: "See the answers",
        tryAgain: "Play again",
        anotherQuiz: "Pick another quiz",
        backLessons: "Back to lessons",
        yourAnswer: "You said",
        correctAnswer: "Right answer",
        showHint: "Need a clue?",
        hideHint: "Hide the clue",
        hintLabel: "Clue",
        steps: "How to do it",
        correct: "Correct",
        incorrect: "Not quite",
        unlockHint: "Pass all 4 quizzes to win your award.",
        unlocked: "You did it! Your award is ready.",
        locked: "Locked",
        printCertificate: "Get my award",
        certTitle: "Fractions Award",
        certAwarded: "Well done",
        certBody: "You finished every fraction quiz in Fraction Fusion. Great work!",
        certDate: "Date",
        certCompletion: "All 4 quizzes done",
        certClose: "Close",
        certPrint: "Print it",
        transitionLoading: "Loading section...",
        namePromptTitle: "What is your name?",
        namePromptDesc: "We will put this name on your award.",
        saveAndContinue: "Save",
        yourNameHolder: "Type your name",
        stars: "Stars",
        starsEarned: "Stars won",
        starOne: "star",
        starMany: "stars",
        figureLabel: "A picture showing a fraction",
        readyForQuiz: "Ready for the quiz?",
        retakeQuiz: "Play again",
        notStarted: "Not tried yet",
        timeLeft: "Time left",
        timeUp: "Time up!",
        answered: "Answered",
        saveVideos: "Save videos",
        videosSaved: "Videos saved",
        savingVideos: "Saving video {a} of {b}...",
        videosReady: "All videos saved. They now play with no internet.",
        videosPartial: "Saved {a} of {b}. Tap again to finish the rest.",
        offlineLabel: "Videos for offline",
        offlineHelp: "Save the lesson videos so they play with no internet.",
        lockedTitle: "Finish Quiz {n} first",
        lockedBody: "Get {p}% or more on Quiz {n} to open this one.",
        lockedChip: "Locked",
        lockedGo: "Go to Quiz {n}",
        best: "Best",
        start: "Start",
        retake: "Retake",
        quiz: "Quiz",
        action: "Action",
        scoreboardCaption: "Your stars, best score and number of tries for each quiz.",
        lessonsPassed: "Lessons done",
        quizzesAttempted: "Quizzes tried",
        averageBest: "Average score",
        thisAttempt: "This try",
        answerChoices: "Answer choices",
        keyboardHint: "Tip: press 1, 2, 3 or 4",
        genericHint: "Take it one step at a time. Rewrite the numbers, then take away.",
        noAnswer: "No answer",
        backToScore: "Back to my score",
        loadingQuiz: "Getting your quiz ready",
        errorTitle: "The quiz did not open",
        errorGeneric: "Something went wrong. Please try once more.",
        errorFileProtocol: "This page was opened directly from the file system, so the browser blocked the quiz data. Serve the folder over HTTP instead:",
        retry: "Try again",
        defaultLearner: "Fraction Fusion Star",
        nameRequired: "Please type your name first.",
      },
      lessonsData: {
        lesson1: {
          title: "Whole number take away mixed number",
          formalTitle: "Subtracting a Mixed Number from a Whole Number",
          description:
            "Start with a whole number like 4, and take away something like 1 1/2.",
          objectives: [
            "Turn 1 whole into a fraction.",
            "Borrow when the top is too small.",
            "Make your answer as simple as you can.",
          ],
        },
        lesson2: {
          title: "Working with different bottom numbers",
          formalTitle: "Subtracting a Mixed Number from a Proper Fraction",
          description:
            "When the bottom numbers are not the same, make them match first.",
          objectives: [
            "Make the bottom numbers the same.",
            "Rewrite the fractions to match.",
            "Take away, then simplify.",
          ],
        },
        lesson3: {
          title: "Whole number take away a fraction",
          formalTitle: "Subtracting a Proper Fraction from a Whole Number",
          description:
            "Start with a whole number like 3, and take away something like 2/5.",
          objectives: [
            "Borrow 1 from the whole number.",
            "Take away step by step.",
            "Solve word problems.",
          ],
        },
        lesson4: {
          title: "Two mixed numbers",
          formalTitle: "Subtracting Two Mixed Numbers",
          description:
            "Take away one mixed number from another, like 3 1/2 minus 1 3/4.",
          objectives: [
            "Make the bottom numbers the same.",
            "Borrow if you need to.",
            "Check your answer at the end.",
          ],
        },
      },
    },
    tl: {
      name: "Tagalog",
      brand: { tagline: "Edisyon sa Pagbabawas" },
      a11y: { skip: "Tumalon sa nilalaman" },
      loader: { text: "Inihahanda ang mga aralin" },
      progress: { title: "Iyong progreso" },
      quizzes: {
        heading: "Mga Bituin Mo",
        body: "1 bituin kapag pasado, 2 kapag mataas, 3 kapag perpekto. Ipasa ang lahat para sa award mo.",
      },
      about: {
        heading: "Tungkol Dito",
        card1: {
          title: "Isa-isa lang",
          body: "Isang bagay lang ang tinuturo ng bawat aralin, tapos sasanayin mo.",
        },
        card2: {
          title: "Tatlong wika",
          body: "Magbasa at makinig sa English, Tagalog o Bisaya. Palitan mo kahit kailan.",
        },
        card3: {
          title: "Gumagana kahit saan",
          body: "Hindi mo kailangan ng internet. Gumagana na ito sa telepono mo.",
        },
      },
      name: {
        title: "Ano ang pangalan mo?",
        desc: "Ilalagay namin ito sa award mo.",
        label: "Pangalan mo",
        placeholder: "I-type ang pangalan mo",
        save: "I-save",
      },
      confirm: {
        title: "Ihinto ang quiz?",
        body: "Hindi masi-save ang iskor mo ngayon.",
        stay: "Magpatuloy",
        leave: "Ihinto",
      },
      footer: {
        text: "Fraction Fusion. Ginawa para sa mas magandang math session.",
        meta: "Gumagana offline",
      },
      nav: ["Home", "Aralin", "Bituin", "Tungkol"],
      hero: {
        eyebrow: "Matematika \u00b7 Edad 7 hanggang 10",
        title: "Magbawas Tayo ng Fraction!",
        intro:
          "Manood ng apat na maikling video, tapos maglaro ng quiz. Mag-ipon ng bituin!",
        start: "Simulan",
        quiz: "Maglaro ng Quiz",
      },
      lessons: {
        heading: "Pumili ng Aralin",
        body: "Magsimula sa bilang 1. Bawat aralin ay tumutulong sa susunod.",
      },
      settings: {
        button: "Mga Setting",
        title: "Mga Setting",
        languageLabel: "Wika",
        languageHelp: "Pinapalitan ang mga salita sa lahat.",
        musicLabel: "Musika",
        musicHelp: "Kusang humihinto kapag may video.",
      },
      quizText: {
        takeQuiz: "Maglaro",
        videoSoonTitle: "Malapit na ang video",
        videoSoonBody: "Wala pa ang video. Pwede ka pa ring maglaro ng quiz.",
        highestScore: "Pinakamataas",
        bestPercentage: "Pinakamahusay",
        attempts: "Subok",
        question: "Tanong",
        of: "ng",
        remaining: "pa",
        prev: "Balik",
        next: "Susunod",
        finish: "Tapos",
        pass: "Pasado",
        fail: "Subukan ulit",
        excellent: "Ang galing!",
        good: "Magaling!",
        keep: "Okay lang. Subukan ulit.",
        viewSolutions: "Tingnan ang sagot",
        tryAgain: "Ulitin",
        anotherQuiz: "Ibang quiz",
        backLessons: "Balik sa aralin",
        yourAnswer: "Sagot mo",
        correctAnswer: "Tamang sagot",
        showHint: "Gusto ng clue?",
        hideHint: "Itago ang clue",
        hintLabel: "Clue",
        steps: "Paano gawin",
        correct: "Tama",
        incorrect: "Halos tama",
        unlockHint: "Ipasa ang lahat ng 4 na quiz para makuha ang award mo.",
        unlocked: "Ayos! Handa na ang award mo.",
        locked: "Naka-lock",
        printCertificate: "Kunin ang award",
        certTitle: "Award sa Fraction",
        certAwarded: "Mahusay",
        certBody: "Natapos mo ang lahat ng fraction quiz sa Fraction Fusion. Ang galing mo!",
        certDate: "Petsa",
        certCompletion: "Tapos ang 4 na quiz",
        certClose: "Isara",
        certPrint: "I-print",
        transitionLoading: "Naglo-load ng seksyon...",
        namePromptTitle: "Ano ang pangalan mo?",
        namePromptDesc: "Ilalagay namin ito sa award mo.",
        saveAndContinue: "I-save",
        yourNameHolder: "I-type ang pangalan mo",
        stars: "Bituin",
        starsEarned: "Bituing nakuha",
        starOne: "bituin",
        starMany: "bituin",
        figureLabel: "Larawan ng isang fraction",
        readyForQuiz: "Handa na sa quiz?",
        retakeQuiz: "Ulitin",
        notStarted: "Hindi pa nasubukan",
        timeLeft: "Natitirang oras",
        timeUp: "Tapos na ang oras!",
        answered: "Nasagot na",
        saveVideos: "I-save ang video",
        videosSaved: "Naka-save na",
        savingVideos: "Sine-save ang video {a} ng {b}...",
        videosReady: "Naka-save na lahat. Gumagana na kahit walang internet.",
        videosPartial: "Nakasave {a} sa {b}. Pindutin ulit para tapusin.",
        offlineLabel: "Video para offline",
        offlineHelp: "I-save ang mga video para gumana kahit walang internet.",
        lockedTitle: "Tapusin muna ang Quiz {n}",
        lockedBody: "Kumuha ng {p}% o higit pa sa Quiz {n} para mabuksan ito.",
        lockedChip: "Naka-lock",
        lockedGo: "Pumunta sa Quiz {n}",
        best: "Pinakamataas",
        start: "Simulan",
        retake: "Ulitin",
        quiz: "Quiz",
        action: "Aksyon",
        scoreboardCaption: "Ang mga bituin, pinakamataas na iskor at bilang ng subok sa bawat quiz.",
        lessonsPassed: "Aralin na tapos",
        quizzesAttempted: "Quiz na sinubok",
        averageBest: "Karaniwang iskor",
        thisAttempt: "Ngayon",
        answerChoices: "Mga pagpipiliang sagot",
        keyboardHint: "Tip: pindutin ang 1, 2, 3 o 4",
        genericHint: "Isa-isahin mo. Isulat muli ang mga numero, tapos magbawas.",
        noAnswer: "Walang sagot",
        backToScore: "Balik sa iskor ko",
        loadingQuiz: "Inihahanda ang quiz mo",
        errorTitle: "Hindi nabuksan ang quiz",
        errorGeneric: "May mali. Subukan ulit.",
        errorFileProtocol: "Direktang binuksan ang pahinang ito mula sa file system, kaya hinarang ng browser ang datos ng quiz. Gamitin ang HTTP server:",
        retry: "Subukan ulit",
        defaultLearner: "Bituin ng Fraction Fusion",
        nameRequired: "Pakisulat muna ang pangalan mo.",
      },
      lessonsData: {
        lesson1: {
          title: "Buong bilang bawasan ng mixed number",
          formalTitle: "Pagbabawas ng Mixed Number mula sa Buong Bilang",
          description:
            "Magsimula sa buong bilang tulad ng 4, tapos bawasan ng 1 1/2.",
          objectives: [
            "Gawing fraction ang 1 buo.",
            "Manghiram kapag maliit ang itaas.",
            "Gawing pinakasimple ang sagot.",
          ],
        },
        lesson2: {
          title: "Magkaibang ibabang bilang",
          formalTitle: "Pagbabawas ng Mixed Number mula sa Proper Fraction",
          description:
            "Kapag hindi pareho ang ibabang bilang, pagparehuin muna.",
          objectives: [
            "Pagparehuin ang ibabang bilang.",
            "Isulat muli ang fraction para magtugma.",
            "Magbawas, tapos i-simplify.",
          ],
        },
        lesson3: {
          title: "Buong bilang bawasan ng fraction",
          formalTitle: "Pagbabawas ng Proper Fraction mula sa Buong Bilang",
          description:
            "Magsimula sa buong bilang tulad ng 3, tapos bawasan ng 2/5.",
          objectives: [
            "Manghiram ng 1 sa buong bilang.",
            "Magbawas nang hakbang-hakbang.",
            "Sagutin ang mga word problem.",
          ],
        },
        lesson4: {
          title: "Dalawang mixed number",
          formalTitle: "Pagbabawas ng Dalawang Mixed Numbers",
          description:
            "Bawasan ang isang mixed number ng isa pa, tulad ng 3 1/2 minus 1 3/4.",
          objectives: [
            "Pagparehuin ang ibabang bilang.",
            "Manghiram kung kailangan.",
            "Suriin ang sagot sa dulo.",
          ],
        },
      },
    },
    bi: {
      name: "Bisaya",
      brand: { tagline: "Edisyon sa Pagbawas" },
      a11y: { skip: "Ambak sa sulod" },
      loader: { text: "Giandam ang mga leksyon" },
      progress: { title: "Imong progreso" },
      quizzes: {
        heading: "Imong mga Bituon",
        body: "1 bituon kung pasar, 2 kung taas, 3 kung sakto tanan. Ipasar tanan para sa imong award.",
      },
      about: {
        heading: "Mahitungod Niini",
        card1: {
          title: "Usa-usa lang",
          body: "Usa ra ka butang ang gitudlo sa matag leksyon, dayon imo kining praktisan.",
        },
        card2: {
          title: "Tulo ka pinulongan",
          body: "Pagbasa ug paminaw sa English, Tagalog o Bisaya. Usba bisan kanus-a.",
        },
        card3: {
          title: "Molihok bisan asa",
          body: "Dili nimo kinahanglan ang internet. Molihok na kini sa imong telepono.",
        },
      },
      name: {
        title: "Unsa imong ngalan?",
        desc: "Ibutang namo kini sa imong award.",
        label: "Imong ngalan",
        placeholder: "I-type imong ngalan",
        save: "I-save",
      },
      confirm: {
        title: "Hunongon ang quiz?",
        body: "Dili matipigan ang imong iskor karon.",
        stay: "Padayon",
        leave: "Hunong",
      },
      footer: {
        text: "Fraction Fusion. Gihimo para sa mas maayong math session.",
        meta: "Molihok offline",
      },
      nav: ["Home", "Leksyon", "Bituon", "About"],
      hero: {
        eyebrow: "Matematika \u00b7 Edad 7 hangtod 10",
        title: "Magbawas Ta og Fraction!",
        intro:
          "Tan-awa ang upat ka mubo nga video, dayon magdula og quiz. Panguha og bituon!",
        start: "Sugdi",
        quiz: "Magdula og Quiz",
      },
      lessons: {
        heading: "Pilia ang Leksyon",
        body: "Sugdi sa numero 1. Ang matag leksyon motabang sa sunod.",
      },
      settings: {
        button: "Settings",
        title: "Settings",
        languageLabel: "Pinulongan",
        languageHelp: "Giusab ang mga pulong sa tanan.",
        musicLabel: "Musika",
        musicHelp: "Mohunong kini kung naay video.",
      },
      quizText: {
        takeQuiz: "Magdula",
        videoSoonTitle: "Hapit na ang video",
        videoSoonBody: "Wala pa ang video. Makadula ka gihapon og quiz.",
        highestScore: "Pinakataas",
        bestPercentage: "Pinakamaayo",
        attempts: "Sulay",
        question: "Pangutana",
        of: "sa",
        remaining: "pa",
        prev: "Balik",
        next: "Sunod",
        finish: "Human",
        pass: "Pasar",
        fail: "Sulayi pag-usab",
        excellent: "Hayahay!",
        good: "Maayo kaayo!",
        keep: "Okay ra. Sulayi usab.",
        viewSolutions: "Tan-awa ang tubag",
        tryAgain: "Usba",
        anotherQuiz: "Laing quiz",
        backLessons: "Balik sa leksyon",
        yourAnswer: "Imong tubag",
        correctAnswer: "Husto nga tubag",
        showHint: "Gusto og clue?",
        hideHint: "Itago ang clue",
        hintLabel: "Clue",
        steps: "Unsaon pagbuhat",
        correct: "Sakto",
        incorrect: "Duol na",
        unlockHint: "Ipasar ang tanang 4 ka quiz aron makuha ang imong award.",
        unlocked: "Nahimo nimo! Andam na imong award.",
        locked: "Naka-lock",
        printCertificate: "Kuhaa ang award",
        certTitle: "Award sa Fraction",
        certAwarded: "Maayong buhat",
        certBody: "Nahuman nimo ang tanang fraction quiz sa Fraction Fusion. Maayo kaayo!",
        certDate: "Petsa",
        certCompletion: "Human ang 4 ka quiz",
        certClose: "Sirado",
        certPrint: "I-print",
        transitionLoading: "Nag-load sa seksyon...",
        namePromptTitle: "Unsa imong ngalan?",
        namePromptDesc: "Ibutang namo kini sa imong award.",
        saveAndContinue: "I-save",
        yourNameHolder: "I-type imong ngalan",
        stars: "Bituon",
        starsEarned: "Bituon nga nakuha",
        starOne: "bituon",
        starMany: "bituon",
        figureLabel: "Hulagway sa usa ka fraction",
        readyForQuiz: "Andam na sa quiz?",
        retakeQuiz: "Usba",
        notStarted: "Wala pa masulayi",
        timeLeft: "Nahibiling nga oras",
        timeUp: "Human na ang oras!",
        answered: "Natubag na",
        saveVideos: "I-save ang video",
        videosSaved: "Na-save na",
        savingVideos: "Gi-save ang video {a} sa {b}...",
        videosReady: "Na-save na tanan. Modagan na bisan walay internet.",
        videosPartial: "Na-save {a} sa {b}. Pindota usab aron humanon.",
        offlineLabel: "Video para offline",
        offlineHelp: "I-save ang mga video aron modagan bisan walay internet.",
        lockedTitle: "Humana usa ang Quiz {n}",
        lockedBody: "Pagkuha ug {p}% o labaw pa sa Quiz {n} aron maabli kini.",
        lockedChip: "Naka-lock",
        lockedGo: "Adto sa Quiz {n}",
        best: "Pinakataas",
        start: "Sugdi",
        retake: "Balika",
        quiz: "Quiz",
        action: "Aksyon",
        scoreboardCaption: "Ang mga bituon, pinakataas nga iskor ug kadaghanon sa sulay sa matag quiz.",
        lessonsPassed: "Leksyon nga human",
        quizzesAttempted: "Quiz nga gisulay",
        averageBest: "Kasagarang iskor",
        thisAttempt: "Karon",
        answerChoices: "Mga pilianang tubag",
        keyboardHint: "Tip: pindota ang 1, 2, 3 o 4",
        genericHint: "Usa-usaha. Isulat pag-usab ang mga numero, dayon pagbawas.",
        noAnswer: "Walay tubag",
        backToScore: "Balik sa akong iskor",
        loadingQuiz: "Giandam ang imong quiz",
        errorTitle: "Wala maabli ang quiz",
        errorGeneric: "Naay sayop. Sulayi usab.",
        errorFileProtocol: "Kini nga panid gibuksan direkta gikan sa file system, mao nga gibabagan sa browser ang datos sa quiz. Gamita ang HTTP server:",
        retry: "Sulayi usab",
        defaultLearner: "Bituon sa Fraction Fusion",
        nameRequired: "Palihug isulat una imong ngalan.",
      },
      lessonsData: {
        lesson1: {
          title: "Tibuok numero bawasan og mixed number",
          formalTitle: "Pagbawas og Mixed Number gikan sa Whole Number",
          description:
            "Sugdi sa tibuok numero sama sa 4, dayon bawasi og 1 1/2.",
          objectives: [
            "Himoa nga fraction ang 1 ka tibuok.",
            "Panghulam kung gamay ang ibabaw.",
            "Himoa nga pinakasayon ang tubag.",
          ],
        },
        lesson2: {
          title: "Lahi nga ubos nga numero",
          formalTitle: "Pagbawas og Mixed Number gikan sa Proper Fraction",
          description:
            "Kung dili pareho ang ubos nga numero, parehoa kini una.",
          objectives: [
            "Parehoa ang ubos nga numero.",
            "Isulat pag-usab ang fraction aron motakdo.",
            "Pagbawas, dayon i-simplify.",
          ],
        },
        lesson3: {
          title: "Tibuok numero bawasan og fraction",
          formalTitle: "Pagbawas og Proper Fraction gikan sa Whole Number",
          description:
            "Sugdi sa tibuok numero sama sa 3, dayon bawasi og 2/5.",
          objectives: [
            "Panghulam og 1 sa tibuok numero.",
            "Pagbawas sa matag lakang.",
            "Sulbara ang mga word problem.",
          ],
        },
        lesson4: {
          title: "Duha ka mixed number",
          formalTitle: "Pagbawas sa Duha ka Mixed Numbers",
          description:
            "Bawasi ang usa ka mixed number og lain, sama sa 3 1/2 minus 1 3/4.",
          objectives: [
            "Parehoa ang ubos nga numero.",
            "Panghulam kung kinahanglan.",
            "Susiha ang tubag sa katapusan.",
          ],
        },
      },
    },
  };

  // Local files so the app works offline. See assets/videos/README.md for the
  // expected filenames; a missing file falls back to a "coming soon" card.
  const LESSON_VIDEO_MAP = {
    lesson1: {
      en: "assets/videos/lesson1-en.mp4",
      tl: "assets/videos/lesson1-tl.mp4",
      bi: "assets/videos/lesson1-bi.mp4",
    },
    lesson2: {
      en: "assets/videos/lesson2-en.mp4",
      tl: "assets/videos/lesson2-tl.mp4",
      bi: "assets/videos/lesson2-bi.mp4",
    },
    lesson3: {
      en: "assets/videos/lesson3-en.mp4",
      tl: "assets/videos/lesson3-tl.mp4",
      bi: "assets/videos/lesson3-bi.mp4",
    },
    lesson4: {
      en: "assets/videos/lesson4-en.mp4",
      tl: "assets/videos/lesson4-tl.mp4",
      bi: "assets/videos/lesson4-bi.mp4",
    },
  };

  window.LanguageService = {
    LANGUAGES,
    LESSON_VIDEO_MAP,
  };
})();
